name: Build and Release

on:
  push:
    branches: 
      - "main"
      - "feature/**"
      - "version/*"
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paper-version: ['1.21-R0.1-SNAPSHOT', '1.21.5-R0.1-SNAPSHOT']
    permissions:
      contents: write # Required to create releases

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dpaper.api.version=${{ matrix.paper-version }}
      
    - name: Upload Artifact
      if: ${{ matrix.paper-version == '1.21.5-R0.1-SNAPSHOT' }}
      uses: actions/upload-artifact@v4
      with:
        name: HardcoreWorldReset-Jar
        path: target/HardcoreWorldReset-*.jar
        retention-days: 5

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && matrix.paper-version == '1.21.5-R0.1-SNAPSHOT'
      uses: softprops/action-gh-release@v1
      with:
        files: target/HardcoreWorldReset-*.jar
        generate_release_notes: true
